{{ $project := get .Values.projects .Values.project}}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: {{ include "gitopsName" . }} 
  namespace: {{ .Values.namespace }}
spec:
  interval: {{ .Values.gitOpsInterval }}
  url: {{ .Values.githubPrefix }}/{{ get $project "gitops" }}
  ref:
    semver: {{ get .Values.snapshot .Values.project }}
  secretRef:
      name: {{ .Values.secretRef }}
