apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: {{ include "gitopsName" . }}
  namespace: {{ .Values.namespace }}
spec:
  interval: {{ .Values.kustomizationInterval }}
  sourceRef:
    kind: GitRepository
    name: {{ include "gitopsName" . }}
  path: "{{ .Values.path}}" 
  prune: true
